### ISSUE TITLE
vim-showtime + vim-ft-clojure = oh...

### ISSUE THREAD

**Issue by ujihisa** [thinca/vim-showtime#5]
vim-ft-clojureのsyntax highlightingがshowtime上で利用できない模様です。

markdownで

``````
```clojure
(doseq [x (range 1 10)]
  (let [y (inc x)]
    (prn (* y 2))))
```
``````

と書いて:ShowTimeStartしたのがこちらとなっております。

![](http://cache.gyazo.com/718cdc9aa27d2598cdc5ac6a6e55efe9.png)

これはこのようになるべきです。

![](http://gyazo.com/debae1e4e156d29595444659789877e4.png)

**Comment by thinca** [comment]
@ujihisa 
構造をがっつり変えた結果これも直った可能性があります。

**Comment by ujihisa** [comment]
![](https://igyazo.com/8612d9ca4f5130de75e6493fccd2f996.png)

神
